name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out Repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build SampleCommunicator
      working-directory: ./SampleCommunicator
      run: |
        chmod +x gradlew && \
        ./gradlew clean build --no-daemon
