name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with: 
        ref: ${{github.ref}}     
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build SGrJavaSamples
      run: |
        cd ./SGrJavaSamples
        chmod +x gradlew
        ./gradlew build

